### ISSUE TITLE
Option to also move cursor

### ISSUE THREAD

**Issue by distbit0** [martixy/obsidian-ctrl-arrow-scroll#1]
Hey this is a great plugin, thanks for making it. I really like that it allows me to scroll by multiple lines without scrolling by an entire page via page up/page down, which I find a bit disorienting and often more than I wanted to scroll. 

I would find it very useful if this extension had an option to also move the cursor while scrolling, so that I can easily start editing once I scroll to the desired position on the page, otherwise I need to use the arrow keys to slowly bring the cursor to where I scrolled, defeating the purpose of this plugin for me.

Very interested in your thoughts or whether I am just missing something and the above can be achieved via some other means! :)

thx

**Comment by martixy** [comment]
Ah, it's probably possible to do. However I am not currently using Obsidian. Right now this plugin is provided as-is.

You could check back in a month or two.
